name: release
on:
  release:
    types: [published]

jobs:
  test-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: MambaList
      - name: run tesh sh
        run: |
          cd ${{ github.workspace }}/MambaList
	  ./hello.sh
     outputs:
       job-status: success
